config/routes.rb
Rails.application.routes.draw do
  get 'book_comments/create'
  get 'book_comments/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to: 'homes#top'

  resources :books, only: [:new, :index, :show, :edit, :update, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]

  get '/home/about' => "homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    has_one_attached :profile_image
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

  def favorited_by?(user)
      favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image

    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
    redirect_back(fallback_location: root_path)
    else
      @user = @book.user
      render template: "books/show"
    end
  end

  def destroy
    book = Book.find(params[:book_id])
    comment = book.book_comments.find(params[:id])
    if book.user_id == current_user.id
    comment.destroy
    redirect_back(fallback_location: root_path)
    else
    redirect_back(fallback_location: root_path)
    end
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have cerated book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render "index"
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @user = current_user
      render "edit"
    else
      redirect_to book_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      render "edit"
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to '/books'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)#なぜできたのか調べる。
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @user = current_user
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件の error が発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="inputTitle">Title</label><br/>
          <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"title"%><br/>
        </div>
        <div class="form-group">
          <label for="inputBody">Opinion</label><br/>
          <%= f.text_field :body, placeholder:"body" %><br/>
        </div>
        <div class="form-group">
        <%= f.submit "Update Book" %>
        </div>
      <% end %>

      <%= link_to 'Show', book_path(@book.id) %> | <%= link_to 'Back', '/books' %>
    </div>
  </div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      <p><%= @user.name %></p>
      <p><%= @user.introduction %></p>
      <div class='row'>
        <%= link_to edit_user_path(@user.id), {class: "btn btn-primary btn-block"} do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
        <%= form_with model: Book.new do |f| %>
          <div class="form-group">
            <h4>Title</h4>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <h4>Opinion</h4>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', {class: "btn btn-success"} %>
          </div>
        <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table>
          <t.head>
            <tr>
              <th></th>
              <th><strong>Title</strong></th>
              <th><strong>Opinion</strong></th>
            </tr>
          </t.head>
          <% @books.each do |book| %>

          <t.body>
            <tr>
              <td><span>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image %>
                <% end %>
              </span></td>
              <td><span><%= link_to book.title, book_path(book.id), class: "show"  %></span></td>
              <td><span><%= book.body %></span></td>

              <td><span><% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fas fa-heart text-danger"></i><%= book.favorites.count %>
                  <% end %>
                </p></span></td>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </P>
              <% end %>
              <td><span>
                <p>
                  <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
                </p></span>
              </td>

            </tr>
          </t.body>
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      <%= image_tag @user.get_profile_image %>
      <p><%= @user.name %></p>
      <p><%= @user.introduction %></p>
      <div class='row'>
        <%= link_to edit_user_path(@user.id), {class: "btn btn-primary btn-block"} do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>


      <h2 class="mt-3">New book</h2>
        <%= form_with model: Book.new do |f| %>
          <div class="form-group">
            <h4>Title</h4>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <h4>Opinion</h4>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', {class: "btn btn-success"} %>
          </div>
        <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table>
          <t.head>
            <tr>
              <th></th>
              <th><strong>Title</strong></th>
              <th><strong>Opinion</strong></th>
            </tr>
          </t.head>

          <t.body>
            <tr>
              <td><span><%= image_tag @book.user.get_profile_image %></span></td>
              <td><span><%= @book.title %></span></td>
              <td><span><%= @book.body %></span></td>
              <% if @user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "edit btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" =>  "Are you sure？", class: "delete btn-primary" %></td>
              <% end %>

              <td><span><% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fas fa-heart text-danger"></i><%= @book.favorites.count %>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="fas fa-heart"></i><%= @book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
              </span></td>

            </tr>
            <tr>
            <td><span><%= link_to @user.name, user_path(@user.id) %></span></td>
            </tr>
          </t.body>
        </table>

        <% if @book_comment.errors.any? %>
          エラーが発生しました。
          <% @book_comment.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
        <% end %>

        <div>
          <p>コメント件数：<%= @book.book_comments.count %></p>
              <% @book.book_comments.each do |book_comment| %>
                <p><%= image_tag book_comment.user.get_profile_image %></p>
                <%= book_comment.user.name %>
                <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
                <% if book_comment.user_id == current_user.id %>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, "data-confirm" =>  "Are you sure？", class: "delete btn-primary" %>
                <% end %>
              <% end %>
        </div>

        <div>
          <%= form_with model: [@book, @book_comment] do |f| %>
            <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
          <% end %>
        </div>

    </div>
  </div>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, {class: "btn btn-primary btn-block"} %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, {class: "btn btn-success btn-block"} %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="container">
            <div class="navbar-brand nav-link-text-white">
              <% if user_signed_in? %>
                <%= link_to user_path(current_user.id) do %>
                  <span class="text-white">Bookers</span>
                <% end %>
              <% else %>
                <%= link_to root_path do %>
                  <span class="text-white">Bookers</span>
                <% end %>
              <% end %>
            </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


          <% if user_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li>
                <%= link_to user_path(current_user), {class: "text-white"} do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>


              <li>
                <%= link_to  users_path, {class: "text-white"} do %>
                <i class="fas fa-users"></i> Users
                <% end %>
              </li>

              <li>
                <%= link_to books_path, {class: "text-white"} do %>
                <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>

              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="text-white fas fa-sign-out-alt"></i> <span class="text-white">Log out</span>
                <% end %>
              </li>

            </ul>
          </div>

          <% else %>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li><%= link_to root_path, {class: "text-white"} do %>
              <i class="fas fa-home"></i> Home
            <% end %>
            </li>

            <li>
              <%= link_to '/home/about', {class: "text-white"} do %>
              <i class="fas fa-link"></i> About
              <% end %>
            </li>

            <li>
              <%= link_to new_user_registration_path, {class: "text-white"} do %>
              <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>

            <li>
              <%= link_to new_user_session_path, {class: "text-white"} do %>
              <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
            </li>

            </ul>
          </div>
          <% end %>
        </div>
      </nav>

    </header>
    <%= flash[:notice] %>

    <%= yield %>

    <footer>
      <div class='container mt-5'>
    	  <div class='row'>
      	  <div class='mx-auto'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <%= @user.errors.count %>件の error が発生しました
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="inputName">Name</label><br/>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%><br/>
          </div>
          <div class="form-group">
            <label for="inputProfileImage">ProfileImage</label><br/>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br/>
          </div>
          <div class="form-group">
            <label for="inputIntroduction">Introduction</label><br/>
            <%= f.text_area :introduction, placeholder:"introduction" %><br/>
          </div>
          <div class="form-group">
            <%= f.submit "Update User" %>
          </div>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image %>
        <p><%= @user.name %></p>
        <p><%= @user.introduction %></p>
      <div class='row'>
        <%= link_to edit_user_path(@user.id), {class: "btn btn-primary btn-block"} do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
        <%= form_with model: Book.new do |f| %>
          <div class="form-group">
            <h4>Title</h4>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <h4>Opinion</h4>
              <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', {class: "btn btn-success"} %>
          </div>
        <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
          <table>
            <t.head>
              <tr>
                <th><strong>image</strong></th>
                <th><strong>Title</strong></th>
                <th></th>
              </tr>
            </t.head>
            <% @users.each do |user| %>
            <t.body>
              <tr>
                <td><span><%= image_tag user.get_profile_image %></span></td>
                <td><span><%= user.name %></span></td>
                <td><%= link_to "Show", user_path(user.id), class: "show" %></td>

              </tr>
            </t.body>
            <% end %>
          </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      <%= image_tag @user.get_profile_image %>
      <p><%= @user.name %></p>
      <p><%= @user.introduction %></p>
      <div class='row'>
        <%= link_to edit_user_path(@user.id), {class: "btn btn-primary btn-block"} do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

     <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new do |f| %>
        <div class="form-group">
          <h4>Title</h4>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h4>Opinion</h4>
            <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', {class: "btn btn-success"} %>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
          <table>
            <t.head>
              <tr>
                <th></th>
                <th><strong>Title</strong></th>
                <th><strong>Opinion</strong></th>
              </tr>
            </t.head>

            <% @books.each do |book| %>
            <t.body>
              <tr>
                <td><span>
                  <%= link_to user_path(@user.id) do %>
                    <%= image_tag @user.get_profile_image %>
                  <% end %>
                </span></td>
                <td><span><%= link_to book.title, book_path(book.id) %></span></td>
                <td><span><%= book.body %></span></td>

                <td><span><% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fas fa-heart text-danger"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="fas fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>

                <td><span><p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p></span></td>

                </span></td>
              </tr>
            </t.body>
            <% end %>

          </table>
    </div>
  </div>
</div>